Make prefix not being recognised as dirs anymore
drivendataorg/cloudpathlib pull request #244
Opened 2022-08-04 16:56 UTC by frndmg

Fixes #208

2022-08-05 17:47 UTC, pjbull requested changes
Thanks @frndmg! We have to get this onto a branch rather than a fork to do the live tests, but lets make the updates here for the tests first.

2022-08-05 17:47 UTC, pjbull commented on tests/test_s3_specific.py
> +    if not s3_like_rig.live_server:
I think we can/should run this against the mocked backend too.

2022-08-05 17:47 UTC, pjbull commented on tests/test_s3_specific.py
> +    assert response["ResponseMetadata"]["HTTPStatusCode"] == 200
I think that we can just use one of the files that gets populated by the rig automatically (for example, like we do here):
https://github.com/drivendataorg/cloudpathlib/blob/2e52c0515547e998e0b7c84e667627df4ac332b6/tests/test_cloudpath_file_io.py#L17-L19

2022-08-10 21:26 UTC, pjbull commented
Thanks @frndmg! Once CI passes here, I'll pull over to a local branch to run the tests against live servers

2022-08-10 21:28 UTC, pjbull commented
Actually, would you mind adding a note in the HISTORY.md as well? I believe you need to start a new "unreleased" section. Here's an old one for reference:
https://github.com/drivendataorg/cloudpathlib/blob/85268c8470f7aa279691eaa96caaaa8652d20204/HISTORY.md?plain=1#L3-L5

2022-08-11 08:03 UTC, frndmg commented
@pjbull feel free to update the message in the `HISTORY.md` if you want

2022-08-11 15:55 UTC, merged