Added with_stem support
drivendataorg/cloudpathlib pull request #290
Opened 2022-11-20 17:36 UTC by Gilthans

#287

2022-11-21 22:08 UTC, pjbull commented
Thanks @Gilthans, could you add:
 - [ ] test
 - [ ] update methods table (you can run [this script](https://github.com/drivendataorg/cloudpathlib/blob/master/docs/make_support_table.py))
 - [ ] update docs with note for `AnyPath` that some cloudpathlib methods may only be supported on compatible Python verions
 - [ ] update HISTORY.md

2023-07-22 17:26 UTC, pjbull commented
Hi @Gilthans, would you have a chance to wrap what this PR needs? Should just be the [items above](https://github.com/drivendataorg/cloudpathlib/pull/290#issuecomment-1322713716) after rebasing onto the latest.

2023-07-23 14:43 UTC, Gilthans commented
Sure, lost track of this PR completely!

2023-07-23 14:50 UTC, Gilthans commented
> * [ ]  update docs with note for `AnyPath` that some cloudpathlib methods may only be supported on compatible Python verions
Where would you envision this appearing? In the `readme.md`? In the class docstring?

2023-07-23 15:14 UTC, Gilthans commented
Another question: obviously tests are failing for python <3.9. Is there a way to specify that this test should only run on certain python versions?

2023-07-23 16:33 UTC, pjbull requested changes

2023-07-23 16:33 UTC, pjbull commented on cloudpathlib/cloudpath.py
> +        return self._dispatch_to_path("with_stem", stem)
CPython implementation is trivial, so maybe we put this in a try-except and fallback to our backport of their implementation if it is not present:
https://github.com/python/cpython/pull/19295/files#diff-fa525485738fc33d05b06c159172ff1f319c26e88d8c6bb39f7dbaae4dc4105cR859-R862

2023-07-23 16:34 UTC, pjbull commented on cloudpathlib/cloudpath.py
> +        return self._dispatch_to_path("with_stem", stem)
(this means that we won't need to skip the test or make a note about compatible versions)

2023-07-24 15:46 UTC, pjbull approved these changes

2023-07-24 15:47 UTC, merged